language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - nightly

env:
   - YARN_GPG=no
cache: 
  - yarn
  - directories:
    - nearcore-tests/nearcore

before_install:
  - rustup target add wasm32-unknown-unknown
  - nvm install 12
  - nvm use 12
  - npm install -g yarn

install:
  - yarn 

script:
  - yarn test
